# Generated by Django 5.2.1 on 2025-05-29 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='course-images/')),
                ('category', models.CharField(choices=[('IT & Software', 'IT & Software'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('IT & Security', 'IT & Security')], max_length=25)),
                ('type', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], max_length=15)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=25)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('offer_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.instructors')),
            ],
            options={
                'verbose_name': 'Courses',
                'verbose_name_plural': 'Courses',
                'ordering': ['id'],
            },
        ),
    ]
