# Generated by Django 5.2.1 on 2025-05-30 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Area of Expertise',
                'verbose_name_plural': 'Area of Expertise',
            },
        ),
        migrations.AddField(
            model_name='instructors',
            name='area_of_expertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.areaofexpertise'),
        ),
    ]
